# based on close stale issues by Github Actions official account
# https://github.com/actions/stale
name: comment-stale-prs

on:
  schedule:
    - cron: '50 2 * * MON-FRI' # runs at 02:50 every night, monday-friday (actually runs at 04:00 according to github logs)
  workflow_dispatch: # used for testing & manual runs

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      # contents: write # only needed for delete-branch option

    steps:
      - uses: actions/stale@v9

        with:
          stale-pr-label: 'needs-review'
          # close-pr-label: (default value: unset) # this should mean that the 'needs-review' label will be removed on certain activity
          stale-pr-message: 'This PR is stale because it has been open for 1 day(s) with no activity. Please review this PR as soon as possible.'
          days-before-stale: 1
          days-before-close: '-1' # never close an issue or pr
          ignore-updates: 'true' # compare days-before-stale to created_at field instead of updated_at field
